### ISSUE TITLE
Resize + crop

### ISSUE THREAD

**Issue by whisher** [eivindfjeldstad/imagemagick-stream#15]
Hi, sorry to bother you
but what's the syntax to resize + crop an image ?
I want to do like:
```javascript
easyimg.rescrop({
     src:'kitten.jpg', dst:'./output/kitten-thumbnail.jpg',
     width:500,//
     cropwidth:128, cropheight:128,
     x:0, y:0
  }).then(
  function(image) {
     console.log('Resized and cropped: ' + image.width + ' x ' + image.height);
  },
  function (err) {
    console.log(err);
  }
);
```
Thanks in advance.

var resize =im().resize('200x200').gravity('Center').crop('50x150').quality(90);
the code is executed without errors but than in the browser 
I get
The image cannot be displayed because it contains errors

I'm using hapi and also with this code
```javascript
var name = data.file.hapi.filename;
var ext = Path.extname(name);
var thumb = Math.random().toString(36).slice(2);
var path = Config.uploadsPath + '/' + thumb  + ext;
var resize = Im().resize('150x150').quality(90);
var file = Fs.createWriteStream(path);
file.on('error', function (err) { 
	return reply(Boom.badImplementation(err));
});
data.file.pipe(resize).pipe(file);
data.file.on('end', function (err) { 
	var res = {
		filename: data.file.hapi.filename,
		thumb: thumb + ext,
		headers: data.file.hapi.headers
	}
    reply(res);
})
```
I get that error
so I'm wondering If I do something wrong

**Comment by eivindfjeldstad** [comment]
It's difficult to say anything based on your example. Can you provide a minimal case without all the hapi stuff?

**Comment by whisher** [comment]
I've tried to isolate the problem:
http://stackoverflow.com/questions/29912212/hapi-upload-image-resize-with-convert-get-the-image-cannot-be-displayed-because

**Comment by eivindfjeldstad** [comment]
You're not using `imagemagick-stream` in that example. If it's not working when using `exec` then I'm pretty sure the problem is outside this repo.

**Comment by whisher** [comment]
just done on purpose :)

**Comment by whisher** [comment]
Sorry my fault
It should be 
```javascript
var out = data.file.pipe(resize).pipe(file);
    out.on('finish', function (err) { 
      var res = {
        filename: data.file.hapi.filename,
        thumb: thumb + ext,
        headers: data.file.hapi.headers
      };
      reply(res);
    });
```

**Comment by whisher** [comment]
This is the right syntax
```javascript
var resize = Im().resize('300x300').gravity('center').crop('150x150+0+0').quality(90)
```
Thanks for your patience
