### ISSUE TITLE
'finish' event emitted too early. Output file size is zero.

### ISSUE THREAD

**Issue by connyhald** [eivindfjeldstad/imagemagick-stream#16]
If we use a bigger input file, by the time the 'finish' event is emitted the output file is still emtpy.

I've changed the tests to check for file size > 0 and added a bigger test image. Please have a look:

https://github.com/connyhald/imagemagick-stream/commit/d73e1fd3e1192d6e16005ad463ec9663de0262e4

With that change all 3 test fail.

**Comment by connyhald** [comment]
However: Listening to 'close' on the file output stream seems to work.

**Comment by eivindfjeldstad** [comment]
What version of Node is this?

**Comment by connyhald** [comment]
Node v0.10.36
ImageMagick 6.8.8-10 Q16 x86_64 2015-03-10

**Comment by eivindfjeldstad** [comment]
I've updated the tests and added a note to the readme. We should listen to the `finish` event on the write stream instead. Released as 3.0.0

**Comment by connyhald** [comment]
Thanks a lot!
