### ISSUE TITLE
Stream 'end' event sometimes not emitted 

### ISSUE THREAD

**Issue by eugeneos** [eivindfjeldstad/imagemagick-stream#17]
I ran into a case when I'm not getting an 'end' event from the stream returned from imagemagick-stream. Unfortunately, I don't have a small repro, but my setup is something like this:
* Starting with stream from an HTTP request (specifically, an uploaded file from *multiparty* component)
* This stream is piped into 4 streams: 
  * "A" - used for parsing EXIF information out of an uploaded image, not with imagemagick
  * "B" - passed to AWS SDK as-is for upload to S3
  * "C" - used for image resizing. It is piped into imagemagick-stream, and the result is further piped into "C1" and "C2". Then, "C1" is used to get the resulting byte size (I just count the total chunk.length on C1.'data' events), and when I get C1.'end' I use the C2 stream to upload to S3 (because unfortunately, S3 requires up-front knowledge of the file size being uploaded)
  * "D" - used for image resizing, exaclty as "C" but with a different image size (also piped to imagemagick-stream, then to D1/D2, etc)

In this setup, for large enough images, everything works fine except that I never get the D1.'end' event (even though I get C1.'end')! It's not 100% reproducible but pretty close to it.

It seems that imagemagick-stream is not emitting the 'end' event for some reason. I added the following code to ImageMagick.prototype.spawn and this fixes the issue:
```javascript
var self=this;
proc.on('close', function() {
  self.emit('end');
});
```
See https://github.com/eugeneos/imagemagick-stream/blob/FixStreamEndBug/index.js

If this is an ok fix, I'd be happy to open a pull request. Or perhaps I'm doing something wrong?

**Comment by eivindfjeldstad** [comment]
hmm. It's very hard to do anything without a failing test case. streams are such a huge mess with all the different versions of node

**Comment by eivindfjeldstad** [comment]
This issue is quite old. Please let me know if it's still a problem in newer versions.
