### ISSUE TITLE
Annotating

### ISSUE THREAD

**Issue by sumanla13a** [eivindfjeldstad/imagemagick-stream#19]
I added `im().set('annotate', '+0+20 "text'")`. But it says 
`Error: convert: invalid argument for option `-annotate': +0+20 "text"`

how do we do this?
Also does adding higher density while streaming work?

**Comment by eivindfjeldstad** [comment]
fixed in 4.1.0. Use `.annotate('+0+20', "'text'")`

**Comment by sumanla13a** [comment]
@eivindfjeldstad  great thanks :)
